repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-added-large-files
  - id: check-json
  - id: debug-statements
  - id: detect-aws-credentials
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: flake8
  - id: trailing-whitespace

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.8
