name: build status

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint with ruff
        uses: astral-sh/ruff-action@v2
        with:
          src: "./aws_log_parser"
      - name: Test with pytest
        run: |
          pip install pipx
          pipx install poetry
          poetry install
          poetry run pytest
